appVersion: v1
kind: Service
metadata: 
  name: uss-backend-github-actions-gke
spec: 
  selector:
    app: uss-backend-github-actions-gke
  type: LoadBalancer
  ports:  
  - port: 80
    targetPort: 18080    